# Generated by Django 4.1 on 2022-09-02 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='depart',
            field=models.CharField(choices=[('선택안함', '선택안함'), ('영업부', '영업부'), ('관리부', '관리부'), ('경리부', '경리부'), ('개발부', '개발부')], max_length=50, verbose_name='부서'),
        ),
    ]
